[pytest]
pythonpath = . API_SCHEMAS tests checker sendler
env_files = 
    sendler/sendler.env
env = 
    PRIVATE_KEY_PATH=API_SCHEMAS/private_key.pem
    PUBLIC_KEY_PATH=API_SCHEMAS/public_key.pem
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function