"""empty message

Revision ID: f5c01da822ed
Revises: d96e757817fc
Create Date: 2026-06-30 19:57:06.189392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c01da822ed'
down_revision: Union[str, Sequence[str], None] = 'd96e757817fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_url_key'), 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('items_url_key'), 'items', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
